{% set name = "pygalmesh" %}
{% set version = "0.6.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: f0166d8858432cefc930757206678024e490f10bcf46779fd549e533a125d3dc
  patches:
    - patches/0001-relax-test-tolerance.patch
    - patches/0002-Do-not-force-C-standard-library.-Compiler-will-choos.patch
    - patches/0003-Relax-tolerance-in-test_volume_from_surface.patch

build:
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - pip
    - eigen
    - cgal-cpp >=5.0.0,<6
    - pybind11 >=2.2
    - mpfr
    - gmp   # [unix]
    - mpir  # [win]
  run:
    - python
    - meshio >=4.0.0,<5.0.0

test:
  imports:
    - pygalmesh
  requires:
    - pytest
    - numpy
  source_files:
    - test
  commands:
    - pytest

about:
  home: https://github.com/nschloe/pygalmesh/
  license: GPL-3.0
  license_family: GPL
  #license_file: LICENSE
  summary: 'A Python frontend to CGAL’s 3D mesh generators.'
  description: |
    pygalmesh is a Python frontend to CGAL’s 3D mesh generation capabilities. pygalmesh makes it easy to create high-quality 3D volume meshes, periodic volume meshes, and surface meshes. 
  doc_url: https://github.com/nschloe/pygalmesh
  dev_url: https://github.com/nschloe/pygalmesh

extra:
  recipe-maintainers:
    - nschloe
    - flothesof
