{% set name = "go-bindata" %}
{% set version = "3.0.7" %}
{% set sha256 = "77a7214479e5ce9004e4afa6d0eb8ce14289030fadc55a3444249ab1fe2c7980" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/jteeuwen/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  binary_relocation: False

requirements:
  build:
    - go

test:
  commands:
    - go-bindata --version

about:
  home: https://github.com/jteeuwen/go-bindata
  license: Public Domain
  license_url: http://creativecommons.org/publicdomain/zero/1.0
  license_file: LICENSE
  summary: A small utility which generates Go code from any file. Useful for embedding binary data in a Go program.
  description: |
    This package converts any file into managable Go source code. Useful for
    embedding binary data into a go program. The file data is optionally gzip
    compressed before being converted to a raw byte slice. It comes with a
    command line tool in the go-bindata sub directory. This tool offers a set
    of command line options, used to customize the output being generated.
  dev_url: https://github.com/jteeuwen/go-bindata

extra:
  recipe-maintainers:
    - nehaljwani
